### ISSUE TITLE
Update demo screenshot to animation

### ISSUE THREAD

**Issue by dbarnett** [google/vim-searchindex#1]
The demo image is nice, but it would showcase the plugin's functionality better if it was animated, like the demo image in the README for https://github.com/Valloric/YouCompleteMe is.

**Comment by rburny** [comment]
Do you know what tools it was created with?

**Comment by dbarnett** [comment]
@Valloric Hey Val, I can't remember, but I think you said you did some non-trivial rigging up of tools to get that animated gif "screencast" of YCM. Do you have details handy?

**Comment by Valloric** [comment]
Ugh, this was like years ago. I believe I followed advice from [this askubuntu thread](http://askubuntu.com/q/107726/343402).

Roughly, the steps are:
1. Record a screencast video file with any of a dozen available options.
2. `ffmpeg -i input.mov output/image%08d.gif`
3. `gifsicle --loop -O3 --delay 4 output/*.gif > anim.gif`

The `--delay` param is important; it's the number of milliseconds between frames. You can use it to tune the speed of the gif.
