### ISSUE TITLE
Broken in MacVim

### ISSUE THREAD

**Issue by dave-kennedy** [google/vim-searchindex#12]
Issue #11 may have been alluding to this issue.

Basically, the `msg` variable is never displayed in the command line. However, if the anything else is echoed right before or after it, both are displayed.

``` vim
function! s:PrintMatches()
  let dir_char = v:searchforward ? '/' : '?'
  if line('$') > g:searchindex_line_limit
    let msg = '[MAX]  ' . dir_char . @/
  else
    " If there are no matches, search fails before we get here. The only way
    " we could see zero results is on 'g/' (but that's a reasonable result).
    let [current, total] = searchindex#MatchCounts()
    let msg = '[' . current . '/' . total . ']  ' . dir_char . @/
  endif

  echo "here"
  echo msg

  " foldopen+=search causes search commands to open folds in the matched line
  " - but it doesn't work in mappings. Hence, we just open the folds here.
  if &foldopen =~# "search"
    normal! zv
  endif
endfunction
```

The above will result in the following displayed in the command line (the search string I used was "echo msg"):

<img width="443" alt="screen shot 2016-08-18 at 11 15 40 am" src="https://cloud.githubusercontent.com/assets/13735532/17783410/27112502-6535-11e6-82cb-1e11dccde7f9.png">

If instead I put the `echo "here"` right after `echo msg`, this is the result:

<img width="454" alt="screen shot 2016-08-18 at 11 18 13 am" src="https://cloud.githubusercontent.com/assets/13735532/17783480/7cf91f56-6535-11e6-99f1-28d188165b68.png">

Thing is it works just fine if I run Vim in a terminal. It's just in MacVim that the problem occurs.

I have no other plugins running (not even Pathogen).

**Comment by yliu120** [comment]
It turns out that this is a bug of MacVim. Please update to the latest MacVim and it will fix this issue.

**Comment by dave-kennedy** [comment]
That did it. Thanks!
