### ISSUE TITLE
Feature request - Add an option not to jump to prev/next instance

### ISSUE THREAD

**Issue by JoshMermel** [google/vim-searchindex#13]
I often want to search for the word under the cursor without losing my cursor position. I suspect I'm not the only person who does this (http://stackoverflow.com/questions/4256697/vim-search-and-highlight-but-do-not-jump).

Because of the way vim-searchindex maps *, I can't seem to map this in my vimrc. It would be nice if that option were supported within the plugin.

**Comment by rburny** [comment]
What you are trying to achieve can already by done through the mappings.

First, to override the plugin mappings, you can use `autocmd VimEnter *`. Second, you can use mappings from the linked thread, just add `<Plug>SearchIndex` at the end to display the counts.
Putting these together:

```
autocmd VimEnter * call <SID>OverridePluginSettings()
function! s:OverridePluginSettings()
  nmap <silent> * :let @/='\<'.expand("<cword>").'\>'<CR>:set hls<CR><Plug>SearchIndex
  nmap <silent> # :let @/='\<'.expand("<cword>").'\>'<CR>:let v:searchforward=0<CR>:set hls<CR><Plug>SearchIndex
endfunction
```

Let me know how that works for you. I know having a dedicated option would be more convenient, but I'm trying to prevent having too many of them.

**Comment by JoshMermel** [comment]
That snippet you put there works exactly as you said it would - thank you!

**Comment by JoshMermel** [comment]
The normal behavior of * and # adds the word under the cursor to your search history. With the above commands, * and # don't add the word under the cursor to your search history. Any suggested workarounds?

**Comment by rburny** [comment]
You could extend the snippet to call `histadd()` function, thus updating history directly: http://vimdoc.sourceforge.net/htmldoc/eval.html#histadd()
