### ISSUE TITLE
moving to match doesn't open fold

### ISSUE THREAD

**Issue by mdavis94538** [google/vim-searchindex#2]
Without this plugin, if I have folding enabled, moving to the next search (including initiating a search) will open all folds necessary to expose the matched text.  With the plugin, the folds don't open; the cursor moves to the correct fold containing the matched text but doesn't open any folds.

**Comment by dbarnett** [comment]
@rburny Is it possible to delegate to `:normal! n` instead of moving the cursor explicitly?

**Comment by rburny** [comment]
@dbarnett what do you mean? The plugin always delegates to Vim's usual commands for search, and just plugs itself after them to display the counts. Here's how `n` is remapped:

```
nmap <silent>n  n<Plug>SearchIndex
```

Unfortunately, Vim seems to only open folds after `n` is typed directly by the user. I've tried the following options (with searchindex uninstalled), and neither of them opens folds:

```
:normal n
:normal! n
:noremap Zn n   followed by   Zn
```

However, I have a workaround - we can use `zv` command to unfold current line. I just need to experiment with it a bit.

**Comment by dbarnett** [comment]
Oh okay, I wasn't looking for the delegation quite as high up as the mapping. The one `n` tacked on there is kind of subtle.

**Comment by rburny** [comment]
OK, I have added the code to open the fold after search. @mdavis94538 , please verify.

Unfortunately, there might be some miscalculation of results when you use folding; I'll file a separate bug for that.

**Comment by mdavis94538** [comment]
Confirmed, the folds open now, and the counts are sometimes off.
