### ISSUE TITLE
The plugin does not seem to respect 'shortmess+=c'

### ISSUE THREAD

**Issue by cheshire** [google/vim-searchindex#22]
I have a `shortmess+=c` in my configuration, but I still get "Pattern not found" error which I need to click enter to dismiss. This wasn't the case without this plugin.

**Comment by rburny** [comment]
Is this related to autocompletion? `shortmess+=c` only affects completion messages.
I verified that after starting Vim with `vi -u NONE` and `set shortmess+=c` I'm still getting "Pattern not found" error during normal searches.
