### ISSUE TITLE
Plugin ignores T flag of shortmess option

### ISSUE THREAD

**Issue by omrisarig13** [google/vim-searchindex#24]
### Background
Every time more than one line should be printed, vim asks you to press enter.
The 'shortmess' option of vim let you choose how to shorten the various printed values in the output, to let the user short the output printed to less than one line, and avoid pressing enter every time more than one line is needed to be printed.
The 'T' option of shortmess enables vim to shorten any string longer than one screen line, replacing the middle of the string with '...'.
### Issue
In this plugin, since the print is happening with simple echo, those options are ignored.
Meaning, when the user searches for a string longer than one screen line, the search would include all the string regardless of the value of shortmess and ask the use to press enter.

**Comment by rburny** [comment]
Thanks for submitting the fix!
