### ISSUE TITLE
Integrate natively with vim

### ISSUE THREAD

**Issue by dbarnett** [google/vim-searchindex#3]
It would be great to see if we could add this feature natively into vim so it could have less overhead and fewer quirks. I filed FR vim/vim#453 in the vim tracker to request it.

**Comment by lifecrisis** [comment]
I agree fully. I actually mentioned this in Pull Request #16. Thanks, @dbarnett, for creating this feature request.  I hope it eventually gets implemented.

**Comment by chrisbra** [comment]
included in Vim as of https://github.com/vim/vim/releases/tag/v8.1.1270

**Comment by infokiller** [comment]
Opened an issue for neovim as well: https://github.com/neovim/neovim/issues/10041

**Comment by infokiller** [comment]
@dbarnett can this be closed now?
It was released in neovim 0.4.0 as well.

**Comment by dbarnett** [comment]
Yep, we should pbb add some notes on this end that you can just install a newer vim/neovim instead if you can, then close this.
