### ISSUE TITLE
Show number of matches on the fly

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [google/vim-searchindex#33]
Is it possible to have it automatically update the number of matches as you type out the regex search query? As opposed to it only showing the number of matches when you hit enter?

**Comment by dbarnett** [comment]
You could request on vim or neovim since search index is natively supported in newer versions (with `:set shortmess-=S`). It would be much more complex to try to solve in a plugin implementation.

**Comment by Sebastian-Nielsen** [comment]
[Solved it](https://github.com/vim/vim/issues/7817#issuecomment-778216088)
